
platform :ios, '5.0'

# For regular projects use:
# pod 'NBUCore',    '~> 2.0.0'

# For NBUCore development:
pod 'CocoaLumberjack', :git => 'https://github.com/rivera-ernesto/CocoaLumberjack.git', :commit => '635987dacce6ecd8a315b66d5422c8abf6107ae0'
pod 'NBUCore',      :path => '../'
